/**
 * FakeCmaRuntime — a deterministic, local, network-free {@link LoopAgentRuntime}.
 *
 * It satisfies the SAME contract as the real CMA adapter, so the orchestration engine
 * runs a genuine PLAN→EXECUTE→EVALUATE→IMPROVE→MEMORY cycle end-to-end with real
 * artifact diffs (it writes files into the loop's git working tree), a streamed event
 * feed, an independent grader that fails the performance gate on the first pass (to
 * exercise IMPROVE), and prompt-cache warmth on cycle > 1. No randomness/time leaks
 * into the cycle's decisions — everything derives from a seed.
 */
import { mkdir, appendFile, writeFile, readFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import type { DeptEvent } from '@departments/events';
import { RUBRIC_CATEGORIES, type RubricCategory, type TokenUsage } from '@departments/shared';
import type {
  EvaluateRequest,
  EventSink,
  GateVerdict,
  LoopAgentRuntime,
  LoopSession,
  LoopSessionInput,
  OutcomeVerdict,
  PhaseRequest,
  PhaseResult,
} from './loop-runtime.js';

// ── deterministic PRNG (mulberry32; no Math.random) ──────────────────────────
function seedFrom(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) h = Math.imul(h ^ s.charCodeAt(i), 16777619);
  return h >>> 0;
}
function rng(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export interface FakeRuntimeOptions {
  /** If false, never fail a gate (skips the IMPROVE iteration). Default true. */
  failFirstPerformanceGate?: boolean;
  /**
   * Simulate a STUCK loop: phases still stream events, but no meaningful artifact is
   * written (only the always-rewritten HANDOFF.md) and no metric moves — so the
   * no-progress detector trips and auto-pauses. Used to demo that guardrail. Default
   * false.
   */
  stall?: boolean;
}

export class FakeCmaRuntime implements LoopAgentRuntime {
  private seq = 0;
  constructor(private readonly opts: FakeRuntimeOptions = {}) {}

  async startSession(input: LoopSessionInput): Promise<LoopSession> {
    return {
      sessionId: `fake-sess-${input.loopId}-${input.runId}-${input.role}`,
      loopId: input.loopId,
      runId: input.runId,
      cycle: input.cycle,
      role: input.role,
      modelId: input.modelId,
      workspaceDir: input.workspaceDir,
    };
  }

  async executePhase(s: LoopSession, req: PhaseRequest, emit: EventSink): Promise<PhaseResult> {
    const rand = rng(seedFrom(`${s.loopId}:${s.runId}:${req.phase}:${req.iteration}`));
    const stall = this.opts.stall ?? false;
    const emitE = (e: Omit<DeptEvent, 'seq'>) => emit({ ...e, seq: this.seq++ } as DeptEvent);
    const ts = () => new Date().toISOString();
    const base = (kind: DeptEvent['kind']) => ({
      id: `${s.runId}-${req.phase}-${s.role}-${this.seq}`,
      loopId: s.loopId,
      runId: s.runId,
      ts: ts(),
      kind,
    });

    emitE({ ...base('status'), kind: 'status', payload: { scope: 'loop', targetId: s.loopId, loopStatus: 'running', phase: req.phase } });
    emitE({ ...base('log'), kind: 'log', payload: { level: 'info', source: 'engine', message: `${req.phase.toUpperCase()} · cycle ${s.cycle}${req.iteration > 0 ? ` · rework #${req.iteration}` : ''} · session ${s.sessionId.slice(-8)}` } });

    const changed: string[] = [];
    let summary = '';
    let memoryNote: string | undefined;

    switch (req.phase) {
      case 'plan': {
        emitE({ ...base('agent_msg'), kind: 'agent_msg', payload: { agentId: `agt-${s.role}`, message: 'Reading HANDOFF + querying memory; refreshing TASKS.md and STRATEGY.md.' } });
        emitE({ ...base('tool_use'), kind: 'tool_use', payload: { agentId: `agt-${s.role}`, tool: 'memory.query', phase: 'result', summary: `top-3 prior insights retrieved` } });
        if (!stall) {
          const task = `- [ ] Cycle ${s.cycle}: ${pick(rand, PLAN_TASKS)}`;
          await appendArtifact(s.workspaceDir, 'TASKS.md', `\n${task}\n`);
          await writeArtifact(s.workspaceDir, 'STRATEGY.md', `# STRATEGY (cycle ${s.cycle})\n\nFocus: ${pick(rand, STRATEGIES)}\nDerived from CEO objectives + last REPORT.md.\n`);
          changed.push('TASKS.md', 'STRATEGY.md');
        }
        summary = stall ? 'No-op plan (stall simulation).' : 'Refreshed TASKS.md (+1 task) and STRATEGY.md from prior memory.';
        break;
      }
      case 'execute': {
        emitE({ ...base('agent_msg'), kind: 'agent_msg', payload: { agentId: `agt-${s.role}`, message: 'Implementing the top task; writing source + notes.' } });
        if (!stall) {
          const rel = `src/generated/feature_${s.cycle}${req.iteration > 0 ? `_fix${req.iteration}` : ''}.ts`;
          const body = `// generated by loop ${s.loopId} · cycle ${s.cycle} · run ${s.runId}\nexport const feature${s.cycle} = () => ${Math.floor(rand() * 1000)};\n`;
          await writeArtifact(s.workspaceDir, rel, body);
          changed.push(rel);
          emitE({ ...base('tool_use'), kind: 'tool_use', payload: { agentId: `agt-${s.role}`, tool: 'fs.write', phase: 'result', summary: `${rel} (+${body.split('\n').length} lines)` } });
          emitE({ ...base('output'), kind: 'output', payload: { agentId: `agt-${s.role}`, text: `Wrote ${rel}; ${req.iteration > 0 ? 'addressed performance gate feedback.' : 'baseline implementation.'}`, streaming: false } });
          const val = 70 + Math.floor(rand() * 25);
          emitE({ ...base('metric'), kind: 'metric', payload: { key: 'throughput', name: 'Throughput', value: val, display: `${val}/100`, delta: Math.floor(rand() * 6), goodDirection: 'up' } });
          summary = `Implemented ${rel}.`;
        } else {
          emitE({ ...base('output'), kind: 'output', payload: { agentId: `agt-${s.role}`, text: 'No actionable task produced a diff this cycle.', streaming: false } });
          summary = 'No diff produced (stall simulation).';
        }
        break;
      }
      case 'improve': {
        emitE({ ...base('agent_msg'), kind: 'agent_msg', payload: { agentId: 'agt-reviewer', message: 'Distilling learnings; writing REPORT.md and reprioritizing the backlog.' } });
        if (!stall) {
          await appendArtifact(s.workspaceDir, 'REPORT.md', `\n## Cycle ${s.cycle}\n- Learning: ${pick(rand, LEARNINGS)}\n- Optimization applied: ${pick(rand, OPTIMIZATIONS)}\n`);
          changed.push('REPORT.md');
        }
        summary = stall ? 'No new learnings to report (stall simulation).' : 'Wrote REPORT.md with this cycle’s learnings + optimizations.';
        break;
      }
      case 'memory': {
        emitE({ ...base('agent_msg'), kind: 'agent_msg', payload: { agentId: 'agt-docs', message: 'Writing HANDOFF.md and distilling one durable insight to memory.' } });
        const handoff = `# HANDOFF\n\n- Cycle: ${s.cycle}\n- Run: ${s.runId}\n- Status: cycle complete; gates passed after IMPROVE.\n- Next: continue from the refreshed TASKS.md; pick the highest-priority open task.\n`;
        await writeArtifact(s.workspaceDir, 'HANDOFF.md', handoff);
        changed.push('HANDOFF.md');
        memoryNote = `Cycle ${s.cycle}: ${pick(rand, INSIGHTS)}`;
        emitE({ ...base('log'), kind: 'log', payload: { level: 'info', source: 'memory', message: `distilled 1 insight → memory store + pgvector` } });
        summary = 'Wrote HANDOFF.md; distilled 1 insight to memory.';
        break;
      }
    }

    emitE({ ...base('log'), kind: 'log', payload: { level: 'info', source: 'engine', message: `${req.phase.toUpperCase()} done — ${changed.length} artifact(s) changed.` } });
    return { summary, changed, memoryNote, usage: this.usageFor(s, req.context) };
  }

  async evaluate(s: LoopSession, req: EvaluateRequest, emit: EventSink): Promise<OutcomeVerdict> {
    const rand = rng(seedFrom(`${s.loopId}:${s.runId}:evaluate:${req.iteration}`));
    const emitE = (e: Omit<DeptEvent, 'seq'>) => emit({ ...e, seq: this.seq++ } as DeptEvent);
    const base = (kind: DeptEvent['kind']) => ({ id: `${s.runId}-eval-${this.seq}`, loopId: s.loopId, runId: s.runId, ts: new Date().toISOString(), kind });

    emitE({ ...base('log'), kind: 'log', payload: { level: 'info', source: 'grader', message: `EVALUATE · independent grader (Opus 4.8) · pass ${req.iteration} · ${req.targetSummary}` } });

    const failPerf = (this.opts.failFirstPerformanceGate ?? true) && req.iteration === 0;
    const gates: GateVerdict[] = RUBRIC_CATEGORIES.map((category: RubricCategory) => {
      const failing = category === 'performance' && failPerf;
      const score = failing ? 55 + Math.floor(rand() * 10) : 88 + Math.floor(rand() * 10);
      return {
        category,
        passed: !failing,
        score,
        notes: failing ? 'Below the success-metric threshold; needs a rework pass.' : 'Meets the rubric.',
      };
    });

    for (const g of gates) {
      emitE({ ...base('debug'), kind: 'debug', payload: { agentId: 'agt-reviewer', message: `gate ${g.category}: ${g.passed ? 'PASS' : 'FAIL'} (${g.score})`, detail: { score: g.score } } });
    }

    const anyFail = gates.some((g) => !g.passed);
    const result = !anyFail
      ? 'satisfied'
      : req.iteration >= req.maxIterations
        ? 'max_iterations_reached'
        : 'needs_revision';

    emitE({ ...base('log'), kind: 'log', payload: { level: anyFail ? 'warn' : 'info', source: 'grader', message: `outcome: ${result}` } });
    return { result, iterations: req.iteration, gates, usage: this.usageFor(s, req.targetSummary) };
  }

  async endSession(s: LoopSession): Promise<void> {
    void s;
  }

  /** Warm prompt cache on cycle > 1: most input tokens become cache reads (~0.1×). */
  private usageFor(s: LoopSession, context: string): TokenUsage {
    const total = 2000 + context.length;
    const warm = s.cycle > 1;
    return {
      inputTokens: warm ? Math.floor(total * 0.1) : total,
      outputTokens: 400,
      cacheReadInputTokens: warm ? Math.floor(total * 0.9) : 0,
      cacheCreationInputTokens: warm ? 0 : total,
    };
  }
}

// ── deterministic content pools ───────────────────────────────────────────────
function pick<T>(rand: () => number, arr: readonly T[]): T {
  return arr[Math.floor(rand() * arr.length)] ?? arr[0]!;
}
const PLAN_TASKS = ['harden the highest-traffic path', 'close the top backlog gap', 'instrument the slow query', 'ship the requested feature increment'] as const;
const STRATEGIES = ['compounding small wins on the critical path', 'cut cycle time, hold quality', 'double down on what the last REPORT proved'] as const;
const LEARNINGS = ['cache hit-rate dominates cost', 'the grader catches over-claiming', 'small diffs review faster'] as const;
const OPTIMIZATIONS = ['froze the prompt prefix', 'reprioritized the backlog by impact', 'tightened the rubric threshold'] as const;
const INSIGHTS = ['the performance gate fails when the diff is too broad — keep changes scoped', 'memory recall improves PLAN quality measurably', 'IMPROVE converges in one rework when feedback is specific'] as const;

// ── artifact write helpers (real files in the loop's git tree) ────────────────
async function writeArtifact(workspaceDir: string, rel: string, content: string): Promise<void> {
  const abs = join(workspaceDir, rel);
  await mkdir(dirname(abs), { recursive: true });
  await writeFile(abs, content, 'utf8');
}
async function appendArtifact(workspaceDir: string, rel: string, content: string): Promise<void> {
  const abs = join(workspaceDir, rel);
  await mkdir(dirname(abs), { recursive: true });
  try {
    const prev = await readFile(abs, 'utf8');
    await writeFile(abs, prev + content, 'utf8');
  } catch {
    await writeFile(abs, content.replace(/^\n/, ''), 'utf8');
  }
}
